#!/bin/bash
function agit {
  staged_count=0
	modified_count=0
	deleted_count=0
  untracked_count=0
  array_count=1

  git diff --name-only --cached | while read line
  do
    file_array[$array_count]=$line
    staged_count=`expr $staged_count + 1`
    array_count=`expr $array_count + 1`
  done

  git ls-files -m | while read line
  do
    file_array[$array_count]=$line
    modified_count=`expr $modified_count + 1`
    array_count=`expr $array_count + 1`
  done
  modified_count=`expr $modified_count + $staged_count`

  git ls-files -d | while read line
  do
    file_array[$array_count]=$line
    deleted_count=`expr $deleted_count + 1`
    array_count=`expr $array_count + 1`
  done
  deleted_count=`expr $deleted_count + $modified_count`

  git ls-files --other --exclude-standard | while read line
  do
    file_array[$array_count]=$line
    untracked_count=`expr $untracked_count + 1`
    array_count=`expr $array_count + 1`
  done
  untracked_count=`expr $untracked_count + $deleted_count`


  if [ $1 = "status" ];then
    agitstatus
  else
    echo "foo"
  fi

  function agitstatus {
    function_count=0
	  echo `git status | head -1`
    if [ $staged_count != 0 ];then
      echo "# Changes to be commited"
      echo "#   (use 'agit reset head to <file_id>...' to unstage)"
      while [ $function_count != $staged_count ];do
        tag=`git status | grep ${file_array[$function_count+1]} | head -n 1 | cut -f 2`
        if [ $function_count -lt 10 ];then
          echo "#       `tput setaf 2`(`expr $function_count + 1`)  - $tag`tput sgr0`"
        else
          echo "#       `tput setaf 2`(`expr $function_count + 1`) - $tag`tput sgr0`"
        fi
        function_count=`expr $function_count + 1`
      done
    fi


    if [ $modified_count != 0 ];then
      echo "#"
			echo "# Changed but not updated:"
			echo "#   (use 'agit add/rm <file_id>...' to update what will be committed)"
			echo "#   (use 'agit checkout -- <file_id>...' to discard changes in working directory)"
      while [ $function_count != $modified_count ];do
        if [ $function_count -lt 10 ];then
          echo "#       `tput setaf 1`(`expr $function_count + 1`)  - modified:   ${file_array[$function_count+1]}`tput sgr0`"
        else
          echo "#       `tput setaf 1`(`expr $function_count + 1`) - modified:   ${file_array[$function_count+1]}`tput sgr0`"
        fi
        function_count=`expr $function_count + 1`
      done
    fi

    if [ $deleted_count != 0 ];then
      echo "#"
      while [ $function_count != $deleted_count ];do
        if [ $function_count -lt 9 ];then
          echo "#       `tput setaf 1`(`expr $function_count + 1`)  - deleted:   ${file_array[$function_count+1]}`tput sgr0`"
        else
          echo "#       `tput setaf 1`(`expr $function_count + 1`) - deleted:   ${file_array[$function_count+1]}`tput sgr0`"
        fi
        function_count=`expr $function_count + 1`
      done
    fi

    if [ $untracked_count != 0 ];then
      echo "#"
      echo "# Untracked files:"
      echo "#   (use 'agit add <file_id>...' to update what will be committed)"
      while [ $function_count != $untracked_count ];do
        if [ $function_count -lt 10 ];then
          echo "#       `tput setaf 1`(`expr $function_count + 1`)  - untracked:   ${file_array[$function_count+1]}`tput sgr0`"
        else
          echo "#       `tput setaf 1`(`expr $function_count + 1`) - untracked:   ${file_array[$function_count+1]}`tput sgr0`"
        fi
        function_count=`expr $function_count + 1`
      done
    fi
    tput sgr0
  }
}
